working - without sanitization

diff --git a/.github/workflows/build_and_unitest.yml b/.github/workflows/build_and_unitest.yml
--- a/.github/workflows/build_and_unitest.yml
+++ b/.github/workflows/build_and_unitest.yml
@@ -116,30 +116,30 @@ jobs:
           target: build
 
       # TODO: Expose the whole profile to the environment and check via compose flags 
-      - name: Check if deploy stage exists
-        id: check_deploy_stage
-        run: |
-          if ! grep -q 'FROM.*AS deploy' ${{ matrix.dockerfile }}; then
-            echo "Deploy stage not found, skipping build"
-            echo "skip_build=true" >> $GITHUB_OUTPUT
-          else
-            echo "Deploy stage found, proceeding with build"
-            echo "skip_build=false" >> $GITHUB_OUTPUT
+      # - name: Check if deploy stage exists
+      #   id: check_deploy_stage
+      #   run: |
+      #     if ! grep -q 'FROM.*AS deploy' ${{ matrix.dockerfile }}; then
+      #       echo "Deploy stage not found, skipping build"
+      #       echo "skip_build=true" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "Deploy stage found, proceeding with build"
+      #       echo "skip_build=false" >> $GITHUB_OUTPUT
 
-      - name: Security Sanitation for Deployment
-        if: ${{ env.skip_build != 'true' }} 
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ${{ matrix.dockerfile }}
-          push: true
-          tags: |
-            ${{ steps.construct-registry-url.outputs.url }}:${{ env.SOURCE_BRANCH }}
-          cache-from: |
-            ${{ steps.construct-registry-url.outputs.url }}:build_${{ env.SOURCE_BRANCH }}
-            ${{ steps.construct-registry-url.outputs.url }}:build_${{ env.TARGET_BRANCH }}
-          builder: ${{ steps.buildx.outputs.name }}
-          target: deploy
+      # - name: Security Sanitation for Deployment
+      #   if: ${{ env.skip_build != 'true' }} 
+      #   uses: docker/build-push-action@v5
+      #   with:
+      #     context: .
+      #     file: ${{ matrix.dockerfile }}
+      #     push: true
+      #     tags: |
+      #       ${{ steps.construct-registry-url.outputs.url }}:${{ env.SOURCE_BRANCH }}
+      #     cache-from: |
+      #       ${{ steps.construct-registry-url.outputs.url }}:build_${{ env.SOURCE_BRANCH }}
+      #       ${{ steps.construct-registry-url.outputs.url }}:build_${{ env.TARGET_BRANCH }}
+      #     builder: ${{ steps.buildx.outputs.name }}
+      #     target: deploy
 
       - name: Run testing suite
         uses: "./.github/templates/test"
